// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD84RfKsRsBiHu3ea-OUxEPcYyxwDGL33E',
    appId: '1:386702274361:web:47d3bd9cd3b4604b7942e8',
    messagingSenderId: '386702274361',
    projectId: 'jjjjjjj-6ace1',
    authDomain: 'jjjjjjj-6ace1.firebaseapp.com',
    storageBucket: 'jjjjjjj-6ace1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2o_IxJqENSBq_EYx0BGGWa1i5mmN7RtM',
    appId: '1:386702274361:android:7aca6c080825a9967942e8',
    messagingSenderId: '386702274361',
    projectId: 'jjjjjjj-6ace1',
    storageBucket: 'jjjjjjj-6ace1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3W6l4dgz6EX-WL5Jn16ld9gx0epKo1KQ',
    appId: '1:386702274361:ios:fb9671c91b2dcd977942e8',
    messagingSenderId: '386702274361',
    projectId: 'jjjjjjj-6ace1',
    storageBucket: 'jjjjjjj-6ace1.appspot.com',
    iosBundleId: 'com.example.newsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3W6l4dgz6EX-WL5Jn16ld9gx0epKo1KQ',
    appId: '1:386702274361:ios:ddb1d48c621535377942e8',
    messagingSenderId: '386702274361',
    projectId: 'jjjjjjj-6ace1',
    storageBucket: 'jjjjjjj-6ace1.appspot.com',
    iosBundleId: 'com.example.newsapp.RunnerTests',
  );
}
